-- ----------------------------
-- TABLE STRUCTURE FOR AUTH_ROLE
-- ----------------------------
DROP TABLE IF EXISTS `AUTH_ROLE`;
CREATE TABLE `AUTH_ROLE`  (
  `ID` VARCHAR(32) NOT NULL COMMENT '主键ID',
  `ROLE_NAME` VARCHAR(128) NULL DEFAULT NULL COMMENT '角色名称',
  `ROLE_TYPE` INT(11) NULL DEFAULT NULL COMMENT '角色类型',
  `DESCRIPTION` VARCHAR(1500) NULL DEFAULT NULL COMMENT '角色描述',
  `CREATOR` VARCHAR(32) NULL DEFAULT NULL COMMENT '创建者',
  `CREATE_TIME` DATETIME(0) NULL DEFAULT NULL COMMENT '创建时间',
  `EDITOR` VARCHAR(32) NULL DEFAULT NULL COMMENT '编辑人',
  `EDIT_TIME` DATETIME(0) NULL DEFAULT NULL COMMENT '更新时间',
  PRIMARY KEY (`ID`)
);
-- ----------------------------
-- RECORDS OF AUTH_ROLE
-- ----------------------------
INSERT INTO `AUTH_ROLE` VALUES ('27e55a01b74342189b00000adminrole', '管理员', 1, '管理员', '27e55a01b74342189b000000000admin', '2020-04-19 19:34:04', NULL, '2020-04-19 19:34:04');
