-- ----------------------------
-- Table structure for AUTH_ROLE
-- ----------------------------
CREATE TABLE "AUTH_ROLE"  (
  "ID" VARCHAR2(32) NOT NULL,
  "ROLE_NAME" VARCHAR2(255) DEFAULT NULL,
  "CREATE_TIME" DATE DEFAULT NULL,
  "UPDATE_TIME" DATE DEFAULT NULL,
  "OP_USERNAME" VARCHAR2(255) DEFAULT NULL,
  "AUTH_MODE" NUMBER(11) DEFAULT NULL,
  PRIMARY KEY ("ID")
);
-- ----------------------------
-- comment for AUTH_ROLE
-- ----------------------------
COMMENT ON COLUMN "AUTH_ROLE"."ID" IS 'ID';
COMMENT ON COLUMN "AUTH_ROLE"."ROLE_NAME" IS '角色名字';
COMMENT ON COLUMN "AUTH_ROLE"."CREATE_TIME" IS '创建时间';
COMMENT ON COLUMN "AUTH_ROLE"."UPDATE_TIME" IS '更新时间';
COMMENT ON COLUMN "AUTH_ROLE"."OP_USERNAME" IS '操作人名字';
COMMENT ON COLUMN "AUTH_ROLE"."AUTH_MODE" IS '权限模式:增删改查1234/查4';
-- ----------------------------
-- Records of AUTH_ROLE
-- ----------------------------
INSERT INTO "AUTH_ROLE" VALUES ('001592803923157000000000000001ar', '管理员', TO_DATE('2020-06-30 16:54:56', 'SYYYY-MM-DD HH24:MI:SS'), TO_DATE('2020-06-30 16:54:56', 'SYYYY-MM-DD HH24:MI:SS'), 'admin', 1234);



