-- ----------------------------
-- Table structure for AUTH_ROLE
-- ----------------------------
CREATE TABLE "AUTH_ROLE"
(
    "ID"          VARCHAR2(32) NOT NULL,
    "ROLE_NAME"   VARCHAR2(128)  DEFAULT NULL,
    "ROLE_TYPE"   NUMBER(11)     DEFAULT NULL,
    "DESCRIPTION" VARCHAR2(1500) DEFAULT NULL,
    "CREATOR"     VARCHAR2(32)   DEFAULT NULL,
    "CREATE_TIME" DATE           DEFAULT NULL,
    "EDITOR"      VARCHAR2(32)   DEFAULT NULL,
    "EDIT_TIME"   DATE           DEFAULT NULL,
    PRIMARY KEY ("ID")
);

-- ----------------------------
-- comment for AUTH_ROLE
-- ----------------------------
COMMENT ON TABLE "AUTH_ROLE" IS '用户角色';
COMMENT ON COLUMN "AUTH_ROLE"."ID" IS '主键ID';
COMMENT ON COLUMN "AUTH_ROLE"."ROLE_NAME" IS '角色名称';
COMMENT ON COLUMN "AUTH_ROLE"."ROLE_TYPE" IS '角色类型';
COMMENT ON COLUMN "AUTH_ROLE"."DESCRIPTION" IS '角色描述';
COMMENT ON COLUMN "AUTH_ROLE"."CREATOR" IS '创建者';
COMMENT ON COLUMN "AUTH_ROLE"."CREATE_TIME" IS '创建时间';
COMMENT ON COLUMN "AUTH_ROLE"."EDITOR" IS '编辑人';
COMMENT ON COLUMN "AUTH_ROLE"."EDIT_TIME" IS '更新时间';

-- ----------------------------
-- Records of AUTH_ROLE
-- ----------------------------
INSERT INTO "AUTH_ROLE" VALUES ('27e55a01b74342189b00000adminrole', '管理员', 1, '管理员', '27e55a01b74342189b000000000admin', TO_DATE('2020-04-19 19:34:04', 'SYYYY-MM-DD HH24:MI:SS'), NULL, TO_DATE('2020-04-19 19:34:04', 'SYYYY-MM-DD HH24:MI:SS'));
